### ISSUE TITLE
How do you change the picture background to white?

### ISSUE THREAD

**Issue by hy-Jeff** [WeiTang114/MVCNN-TensorFlow#16]
hello，How do you change the picture background to white? Because I want to  use another database, but the background of the data is also white.Can you introduce some methods?

**Comment by WeiTang114** [comment]
Hi, it's like this
```
im = cv2.imread(path)  # (0-255)
im = 255. - im
```

**Comment by hy-Jeff** [comment]
Thank you  very much~! 
On 11/30/2017 22:54，Tang Lee<notifications@github.com> wrote：

Hi, it's like this

im = cv2.imread(path)  # (0-255)
im = 255. - im
