### ISSUE TITLE
How to prepare the dataset?

### ISSUE THREAD

**Issue by Metal-joker** [WeiTang114/MVCNN-TensorFlow#17]
Hi, there

I have a little problem when I try to run this project.

How can I transfer my OFF file to this project needed file format?

thanks for any help

**Comment by WeiTang114** [comment]
I'd recommend writing a Blender script in Python to do this.
If you're familiar with OpenGL in C/C++, it is possible (and faster) too. Blender is easier.

**Comment by Metal-joker** [comment]
Thanks for your reply.

I tried Blender but still can't make my dataset like that.

Could you please share that part of code?

thanks again

**Comment by WeiTang114** [comment]
@Metal-joker 
I just uploaded it to github: [https://github.com/WeiTang114/BlenderPhong/](https://github.com/WeiTang114/BlenderPhong/)
Try it out! 😜

**Comment by Metal-joker** [comment]
thanks a lot!

**Comment by hy-Jeff** [comment]
hello,  I want to convert the  background of the picture  to black(new pixel = 255-origin pixel) . However, there still exits some differences  from yours. Could you show me some methods to deal with it? Thank you very much!
![airplane_0001 0](https://user-images.githubusercontent.com/30170531/34512312-889957e2-f09c-11e7-844d-5ca8b2227124.jpg)
![airplane_0001 0](https://user-images.githubusercontent.com/30170531/34512313-88d30276-f09c-11e7-9f6a-f749d8e66cfa.png)

**Comment by WeiTang114** [comment]
@heyuCute, for training and testing the model, the performance should be fine with your data.
If you really need the data like mine, please try [BlenderPhong](https://github.com/WeiTang114/BlenderPhong/). Although mine are generated with C++/OpenGL, those generated with BlenderPhong should look similar.

**Comment by WeiTang114** [comment]
I'm closing this issue as it seems to be solved.
Feel free to reopen it if you met the issue again.
