### ISSUE TITLE
Can we train our model without the pretrained AlexNet model?

### ISSUE THREAD

**Issue by foxfromworld** [WeiTang114/MVCNN-TensorFlow#19]
Hi,

Can we train our model from scratch instead of using the pretrained AlexNet model?
Thank you so much!!

Best regards,

**Comment by WeiTang114** [comment]
Yes.
You can run the training command without `--caffemodel` for training from scratch.
I'm closing the issue. Feel free to reopen it if you encounter any problem. :)

**Comment by foxfromworld** [comment]
Thank you so much
