### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by bonbonjour** [WeiTang114/MVCNN-TensorFlow#23]
thank you for your work! I want to train the network with dataset of modelnet40v1png, but i don't know how to make the train list, can you please tell

**Comment by WeiTang114** [comment]
Please follow the examples in `data_sample/view/`. 
You can write bash / python scripts to generate them.

**Comment by aihaoc** [comment]
I don't know how to make the training list. How did you solve it

**Comment by WeiTang114** [comment]
You can see examples in `data_sample/view/`. The files can be generated either manually or by a program.
