### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/weitang114/Dev/blenderSC/missed_stls.txt'

### ISSUE THREAD

**Issue by xidianxiaofeixian** [WeiTang114/MVCNN-TensorFlow#24]
thank you for your work! I want to create our own 2D dataset from 3D objects (.obj, .stl, and .off), using BlenderPhong, reported a mistake, can you please tell how to solve it.

**Comment by WeiTang114** [comment]
This issue is no relevant to this repo so I'm closing it.
See https://github.com/WeiTang114/BlenderPhong/issues/4 for more discussion.
