### ISSUE TITLE
OpenCV assertion failed, ssize.area()>0 in resize

### ISSUE THREAD

**Issue by ttyang1018** [WeiTang114/MVCNN-TensorFlow#4]
Hi there,

I tried to run the example. My environment is ubuntu 16.04, and OpenCV 2.4.10

But I came into the following assertion failed

![image](https://user-images.githubusercontent.com/13607569/28125021-f2f589b8-6757-11e7-96a8-0cec0c7662d3.png)

Any suggestion?

**Comment by WeiTang114** [comment]
Could you check if the file exists?
I met this problem once because the file was not there and cv2.imread() returned nothing.

**Comment by ttyang1018** [comment]
Do you mean the file alexnet_imagenet.npy?

It's located in the same directory of train.py.

Could I know the version of your opencv? I try to run the same configuration as yours.

**Comment by WeiTang114** [comment]
No, I mean the image file of the view it is reading.
that message happens to me mostly because the image path is wrong and imread returns None.

**Comment by ttyang1018** [comment]
My bad... I neglected to download the modelnet40...
